apiVersion: apps/v1
kind: Deployment
metadata:
  name: du-workload-{{.Replica}}
  annotations:
    # Disable CPU balance with CRIO
    irq-load-balancing.crio.io: "disable"
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
  labels:
    group: load
    svc: du-workload-{{.Replica}}
    redhat-best-practices-for-k8s.com/generic: target
spec:
  replicas: 1
  selector:
    matchLabels:
      name: du-workload-{{.Replica}}
      redhat-best-practices-for-k8s.com/generic: target
  template:
    metadata:
      labels:
        group: load
        name: du-workload-{{.Replica}}
        redhat-best-practices-for-k8s.com/generic: target
    spec:
      runtimeClassName: performance-openshift-node-performance-profile
      containers:
        - image: "{{ .Image }}"
          imagePullPolicy: IfNotPresent
          name: du-workload-{{.Replica}}
          # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
          resources:
            requests:
              cpu: 32000m
              memory: 1024M
              hugepages-1Gi: 16Gi
            limits:
              cpu: 32000m
              memory: 1024M
              hugepages-1Gi: 16Gi
          env:
            - name: stress_cpu
              value: "32"
            - name: stress_vm
              value: "1"
            - name: stress_vm-bytes
              value: "512M"
          volumeMounts:
            {{ range  $volume := .volumes }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.path }}
            {{ end }}
            - name: hugepage
              mountPath: /hugepages
      dnsPolicy: Default
      terminationGracePeriodSeconds: 1
      volumes:
        {{ range  $volume := .volumes }}
        - name: {{ $volume.name }}
          {{ if eq $volume.type "configMap" }}
          configMap:
            name: {{ $volume.name }}
          {{ else if eq $volume.type "secret" }}
          secret:
            secretName: {{ $volume.name }}
          {{ else if eq $volume.type "persistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ $volume.name }}
          {{ end }}
        {{ end }}
        - name: hugepage
          emptyDir:
            medium: HugePages